"""add language to posts

Revision ID: 117789a06c08
Revises: 751bd4791c51
Create Date: 2020-03-28 15:30:41.984916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117789a06c08'
down_revision = '751bd4791c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
